### ISSUE TITLE
PROTOTYPE

### ISSUE THREAD

**Issue by miimss** [Myyyra/StashHunters#16]
- [x] Research and decide a tool to create a prototype (e.g. InVision/Figma)
- [ ] Create a view for frontpage
- - [x] logo
- - [x] register-button
- - [x] sign in-button
- [ ] Create a view for registration
- - [ ] fields for username and email
- - [ ] send-button
- - [ ] cancel-button
- [x] Create a view for map-view
- - [x] navigation (stash, seek, stash list)
- - [x] map
- - [x] search-areas
- [x] Create a view for a stash
- - [x] image
- - [x] name and presentation text
- [x] Create a view for creating a stash
- - [x] button for taking a picture
- - [x] field for name and presentation text
- - [x] save-button
- - [x] cancel-button

**Comment by melliswee** [comment]
Prototype demonstrates a part of the app's functionalities and gives an idea of the style of the app. Considered "done", for now.
